In [1]:
import pandas as pd
from sqlalchemy import create_engine  #Store CSV into DataFrame
import json
from Resources import configmu
import pprint
import pymysql
from pandas.io import sql

In [2]:
csv_file = "population.csv"
pop_data_df = pd.read_csv(csv_file)
pop_data_df.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'NAME', 'ESTIMATESBASE2010',
       'POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012',
       'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015',
       'POPESTIMATE2016', 'POPESTIMATE2017', 'POPESTIMATE2018', 'NPOPCHG_2010',
       'NPOPCHG_2011', 'NPOPCHG_2012', 'NPOPCHG_2013', 'NPOPCHG_2014',
       'NPOPCHG_2015', 'NPOPCHG_2016', 'NPOPCHG_2017', 'NPOPCHG_2018',
       'PPOPCHG_2010', 'PPOPCHG_2011', 'PPOPCHG_2012', 'PPOPCHG_2013',
       'PPOPCHG_2014', 'PPOPCHG_2015', 'PPOPCHG_2016', 'PPOPCHG_2017',
       'PPOPCHG_2018', 'NRANK_ESTBASE2010', 'NRANK_POPEST2010',
       'NRANK_POPEST2011', 'NRANK_POPEST2012', 'NRANK_POPEST2013',
       'NRANK_POPEST2014', 'NRANK_POPEST2015', 'NRANK_POPEST2016',
       'NRANK_POPEST2017', 'NRANK_POPEST2018', 'NRANK_NPCHG2010',
       'NRANK_NPCHG2011', 'NRANK_NPCHG2012', 'NRANK_NPCHG2013',
       'NRANK_NPCHG2014', 'NRANK_NPCHG2015', 'NRANK_NPCHG2016',
       'NRANK_NPCHG2017', 'NRANK_NPCHG2018', 'NRANK_PPCHG2010',
       'NRANK_PPCHG2011', 'NRANK_PPCHG2012', 'NRANK_PPCHG2013',
       'NRANK_PPCHG2014', 'NRANK_PPCHG2015', 'NRANK_PPCHG2016',
       'NRANK_PPCHG2017', 'NRANK_PPCHG2018'],
      dtype='object')

In [3]:
state_json = json.load(open('state_sociological.json'))

In [4]:
state_json

{'data': [{'state': 'Massachusetts',
   'percent_educational_attainment': 38.2,
   'percent_peace_index': 59.92,
   'percent_above_poverty_rate': 88.3,
   'percent_non_religious': 67},
  {'state': 'Maryland',
   'percent_educational_attainment': 37.3,
   'percent_peace_index': 37.1,
   'percent_above_poverty_rate': 89.6,
   'percent_non_religious': 46},
  {'state': 'Colorado',
   'percent_educational_attainment': 35.9,
   'percent_peace_index': 49.48,
   'percent_above_poverty_rate': 87.9,
   'percent_non_religious': 53},
  {'state': 'Connecticut',
   'percent_educational_attainment': 35.6,
   'percent_peace_index': 56.12,
   'percent_above_poverty_rate': 89.2,
   'percent_non_religious': 57},
  {'state': 'New Jersey',
   'percent_educational_attainment': 34.5,
   'percent_peace_index': 47.38,
   'percent_above_poverty_rate': 88.9,
   'percent_non_religious': 45},
  {'state': 'Virginia',
   'percent_educational_attainment': 34,
   'percent_peace_index': 50.46,
   'percent_above_poverty_rate': 88.2,
   'percent_non_religious': 39},
  {'state': 'Vermont',
   'percent_educational_attainment': 33.1,
   'percent_peace_index': 69.06,
   'percent_above_poverty_rate': 87.8,
   'percent_non_religious': 66},
  {'state': 'New York',
   'percent_educational_attainment': 32.4,
   'percent_peace_index': 45.56,
   'percent_above_poverty_rate': 84.1,
   'percent_non_religious': 54},
  {'state': 'New Hampshire',
   'percent_educational_attainment': 32,
   'percent_peace_index': 68.98,
   'percent_above_poverty_rate': 90.8,
   'percent_non_religious': 67},
  {'state': 'Minnesota',
   'percent_educational_attainment': 31.5,
   'percent_peace_index': 67.72,
   'percent_above_poverty_rate': 88.6,
   'percent_non_religious': 51},
  {'state': 'Washington',
   'percent_educational_attainment': 31,
   'percent_peace_index': 64.36,
   'percent_above_poverty_rate': 86.8,
   'percent_non_religious': 55},
  {'state': 'Illinois',
   'percent_educational_attainment': 30.6,
   'percent_peace_index': 42.16,
   'percent_above_poverty_rate': 85.7,
   'percent_non_religious': 49},
  {'state': 'Rhode Island',
   'percent_educational_attainment': 30.5,
   'percent_peace_index': 64.24,
   'percent_above_poverty_rate': 85.2,
   'percent_non_religious': 51},
  {'state': 'California',
   'percent_educational_attainment': 29.9,
   'percent_peace_index': 45.24,
   'percent_above_poverty_rate': 83.6,
   'percent_non_religious': 51},
  {'state': 'Hawaii',
   'percent_educational_attainment': 29.6,
   'percent_peace_index': 64.32,
   'percent_above_poverty_rate': 88.5,
   'percent_non_religious': 53},
  {'state': 'Kansas',
   'percent_educational_attainment': 29.5,
   'percent_peace_index': 48.54,
   'percent_above_poverty_rate': 86.5,
   'percent_non_religious': 45},
  {'state': 'Oregon',
   'percent_educational_attainment': 29.2,
   'percent_peace_index': 58.56,
   'percent_above_poverty_rate': 83.6,
   'percent_non_religious': 52},
  {'state': 'Delaware',
   'percent_educational_attainment': 28.7,
   'percent_peace_index': 37.04,
   'percent_above_poverty_rate': 87,
   'percent_non_religious': 48},
  {'state': 'Utah',
   'percent_educational_attainment': 28.5,
   'percent_peace_index': 65.54,
   'percent_above_poverty_rate': 88.2,
   'percent_non_religious': 36},
  {'state': 'Georgia',
   'percent_educational_attainment': 27.5,
   'percent_peace_index': 39.2,
   'percent_above_poverty_rate': 81.6,
   'percent_non_religious': 34},
  {'state': 'Montana',
   'percent_educational_attainment': 27.4,
   'percent_peace_index': 54.54,
   'percent_above_poverty_rate': 84.8,
   'percent_non_religious': 52},
  {'state': 'Nebraska',
   'percent_educational_attainment': 27.4,
   'percent_peace_index': 61.46,
   'percent_above_poverty_rate': 87.7,
   'percent_non_religious': 46},
  {'state': 'Maine',
   'percent_educational_attainment': 26.9,
   'percent_peace_index': 73.84,
   'percent_above_poverty_rate': 86,
   'percent_non_religious': 66},
  {'state': 'Alaska',
   'percent_educational_attainment': 26.6,
   'percent_peace_index': 44.98,
   'percent_above_poverty_rate': 88.6,
   'percent_non_religious': 55},
  {'state': 'North Carolina',
   'percent_educational_attainment': 26.5,
   'percent_peace_index': 45.72,
   'percent_above_poverty_rate': 82.8,
   'percent_non_religious': 35},
  {'state': 'Pennsylvania',
   'percent_educational_attainment': 26.4,
   'percent_peace_index': 52.5,
   'percent_above_poverty_rate': 86.4,
   'percent_non_religious': 47},
  {'state': 'North Dakota',
   'percent_educational_attainment': 25.8,
   'percent_peace_index': 65.12,
   'percent_above_poverty_rate': 88.9,
   'percent_non_religious': 47},
  {'state': 'Wisconsin',
   'percent_educational_attainment': 25.7,
   'percent_peace_index': 53.96,
   'percent_above_poverty_rate': 86.8,
   'percent_non_religious': 55},
  {'state': 'Arizona',
   'percent_educational_attainment': 25.6,
   'percent_peace_index': 35.66,
   'percent_above_poverty_rate': 81.8,
   'percent_non_religious': 47},
  {'state': 'Texas',
   'percent_educational_attainment': 25.5,
   'percent_peace_index': 35.96,
   'percent_above_poverty_rate': 82.8,
   'percent_non_religious': 36},
  {'state': 'Florida',
   'percent_educational_attainment': 25.3,
   'percent_peace_index': 32.7,
   'percent_above_poverty_rate': 83.4,
   'percent_non_religious': 46},
  {'state': 'New Mexico',
   'percent_educational_attainment': 25.3,
   'percent_peace_index': 42.94,
   'percent_above_poverty_rate': 79.4,
   'percent_non_religious': 43},
  {'state': 'Missouri',
   'percent_educational_attainment': 25.2,
   'percent_peace_index': 35.9,
   'percent_above_poverty_rate': 84.5,
   'percent_non_religious': 40},
  {'state': 'Iowa',
   'percent_educational_attainment': 25.1,
   'percent_peace_index': 62.7,
   'percent_above_poverty_rate': 87.7,
   'percent_non_religious': 45},
  {'state': 'South Dakota',
   'percent_educational_attainment': 25.1,
   'percent_peace_index': 53.64,
   'percent_above_poverty_rate': 85.9,
   'percent_non_religious': 41},
  {'state': 'Michigan',
   'percent_educational_attainment': 24.6,
   'percent_peace_index': 46.12,
   'percent_above_poverty_rate': 83.8,
   'percent_non_religious': 47},
  {'state': 'South Carolina',
   'percent_educational_attainment': 24.3,
   'percent_peace_index': 36.44,
   'percent_above_poverty_rate': 82.1,
   'percent_non_religious': 30},
  {'state': 'Ohio',
   'percent_educational_attainment': 24.1,
   'percent_peace_index': 53.44,
   'percent_above_poverty_rate': 84.2,
   'percent_non_religious': 42},
  {'state': 'Idaho',
   'percent_educational_attainment': 23.9,
   'percent_peace_index': 55.48,
   'percent_above_poverty_rate': 85.2,
   'percent_non_religious': 49},
  {'state': 'Wyoming',
   'percent_educational_attainment': 23.8,
   'percent_peace_index': 54.72,
   'percent_above_poverty_rate': 89.4,
   'percent_non_religious': 46},
  {'state': 'Tennessee',
   'percent_educational_attainment': 23,
   'percent_peace_index': 31.74,
   'percent_above_poverty_rate': 81.8,
   'percent_non_religious': 27},
  {'state': 'Oklahoma',
   'percent_educational_attainment': 22.7,
   'percent_peace_index': 37.78,
   'percent_above_poverty_rate': 83.4,
   'percent_non_religious': 34},
  {'state': 'Indiana',
   'percent_educational_attainment': 22.5,
   'percent_peace_index': 53.1,
   'percent_above_poverty_rate': 84.8,
   'percent_non_religious': 46},
  {'state': 'Alabama',
   'percent_educational_attainment': 22,
   'percent_peace_index': 36.6,
   'percent_above_poverty_rate': 80.8,
   'percent_non_religious': 23},
  {'state': 'Nevada',
   'percent_educational_attainment': 21.8,
   'percent_peace_index': 32.64,
   'percent_above_poverty_rate': 84.6,
   'percent_non_religious': 51},
  {'state': 'Louisiana',
   'percent_educational_attainment': 21.4,
   'percent_peace_index': 19.02,
   'percent_above_poverty_rate': 80.1,
   'percent_non_religious': 29},
  {'state': 'Kentucky',
   'percent_educational_attainment': 21,
   'percent_peace_index': 53.64,
   'percent_above_poverty_rate': 81,
   'percent_non_religious': 37},
  {'state': 'Mississippi',
   'percent_educational_attainment': 19.6,
   'percent_peace_index': 36.6,
   'percent_above_poverty_rate': 78.1,
   'percent_non_religious': 23},
  {'state': 'Arkansas',
   'percent_educational_attainment': 18.9,
   'percent_peace_index': 35.98,
   'percent_above_poverty_rate': 81.3,
   'percent_non_religious': 30},
  {'state': 'West Virginia',
   'percent_educational_attainment': 17.3,
   'percent_peace_index': 56.06,
   'percent_above_poverty_rate': 81.7,
   'percent_non_religious': 31}],
 'sources': {'education': {'source': 'https://en.wikipedia.org/wiki/List_of_U.S._states_by_educational_attainment'},
  'peace': {'source': 'http://www.visionofhumanity.org/#/page/indexes/us-peace-index'},
  'poverty': {'source': 'https://en.wikipedia.org/wiki/List_of_U.S._states_by_poverty_rate'},
  'religion': {'source': 'http://www.pewresearch.org/fact-tank/2016/02/29/how-religious-is-your-state/'}}}

In [5]:
state_df = pd.DataFrame(state_json["data"])
state_df

,percent_above_poverty_rate,percent_educational_attainment,percent_non_religious,percent_peace_index,state
0,88.3,38.2,67,59.92,Massachusetts
1,89.6,37.3,46,37.10,Maryland
2,87.9,35.9,53,49.48,Colorado
3,89.2,35.6,57,56.12,Connecticut
4,88.9,34.5,45,47.38,New Jersey
5,88.2,34.0,39,50.46,Virginia
6,87.8,33.1,66,69.06,Vermont
7,84.1,32.4,54,45.56,New York
8,90.8,32.0,67,68.98,New Hampshire
9,88.6,31.5,51,67.72,Minnesota
10,86.8,31.0,55,64.36,Washington
11,85.7,30.6,49,42.16,Illinois
12,85.2,30.5,51,64.24,Rhode Island
13,83.6,29.9,51,45.24,California
14,88.5,29.6,53,64.32,Hawaii
15,86.5,29.5,45,48.54,Kansas
16,83.6,29.2,52,58.56,Oregon
17,87.0,28.7,48,37.04,Delaware
18,88.2,28.5,36,65.54,Utah
19,81.6,27.5,34,39.20,Georgia
20,84.8,27.4,52,54.54,Montana
21,87.7,27.4,46,61.46,Nebraska
22,86.0,26.9,66,73.84,Maine
23,88.6,26.6,55,44.98,Alaska
24,82.8,26.5,35,45.72,North Carolina
25,86.4,26.4,47,52.50,Pennsylvania
26,88.9,25.8,47,65.12,North Dakota
27,86.8,25.7,55,53.96,Wisconsin
28,81.8,25.6,47,35.66,Arizona
29,82.8,25.5,36,35.96,Texas
30,83.4,25.3,46,32.70,Florida
31,79.4,25.3,43,42.94,New Mexico
32,84.5,25.2,40,35.90,Missouri
33,87.7,25.1,45,62.70,Iowa
34,85.9,25.1,41,53.64,South Dakota
35,83.8,24.6,47,46.12,Michigan
36,82.1,24.3,30,36.44,South Carolina
37,84.2,24.1,42,53.44,Ohio
38,85.2,23.9,49,55.48,Idaho
39,89.4,23.8,46,54.72,Wyoming
40,81.8,23.0,27,31.74,Tennessee
41,83.4,22.7,34,37.78,Oklahoma
42,84.8,22.5,46,53.10,Indiana
43,80.8,22.0,23,36.60,Alabama
44,84.6,21.8,51,32.64,Nevada
45,80.1,21.4,29,19.02,Louisiana
46,81.0,21.0,37,53.64,Kentucky
47,78.1,19.6,23,36.60,Mississippi
48,81.3,18.9,30,35.98,Arkansas
49,81.7,17.3,31,56.06,West Virginia

In [6]:
renamed_state_df = pop_data_df.rename(columns={"NAME":"state", "STATE":"index"})
renamed_state_df

,SUMLEV,REGION,DIVISION,index,state,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,...,NRANK_NPCHG2018,NRANK_PPCHG2010,NRANK_PPCHG2011,NRANK_PPCHG2012,NRANK_PPCHG2013,NRANK_PPCHG2014,NRANK_PPCHG2015,NRANK_PPCHG2016,NRANK_PPCHG2017,NRANK_PPCHG2018
0,10,0,0,0,United States,308758105,309326085,311580009,313874218,316057727,...,X,X,X,X,X,X,X,X,X,X
1,20,1,0,0,Northeast Region,55318430,55380645,55600532,55776729,55907823,...,4,3,3,3,4,4,4,4,4,4
2,20,2,0,0,Midwest Region,66929743,66974749,67152631,67336937,67564135,...,3,4,4,4,3,3,3,3,3,3
3,20,3,0,0,South Region,114563045,114867066,116039399,117271075,118393244,...,1,1,1,1,1,1,1,1,1,1
4,20,4,0,0,West Region,71946887,72103625,72787447,73489477,74192525,...,2,2,2,2,2,2,2,2,2,2
5,40,3,6,1,Alabama,4780138,4785448,4798834,4815564,4830460,...,27,37,38,34,33,35,36,34,34,34
6,40,4,9,2,Alaska,710249,713906,722038,730399,737045,...,45,2,8,11,18,48,37,22,46,49
7,40,4,8,4,Arizona,6392288,6407774,6473497,6556629,6634999,...,4,15,10,7,7,7,9,9,6,4
8,40,3,7,5,Arkansas,2916028,2921978,2940407,2952109,2959549,...,30,22,28,31,38,31,30,26,24,28
9,40,4,9,6,California,37254523,37320903,37641823,37960782,38280824,...,3,26,17,19,20,16,16,20,23,25
10,40,4,8,8,Colorado,5029316,5048281,5121771,5193721,5270482,...,8,6,4,5,5,4,4,10,8,7
11,40,1,1,9,Connecticut,3574147,3579125,3588023,3594395,3594915,...,44,30,42,43,50,46,50,48,44,43
12,40,3,5,10,Delaware,897934,899595,907316,915188,923638,...,32,24,18,18,17,13,15,16,17,12
13,40,3,5,11,District of Columbia,601766,605085,619602,634725,650431,...,35,1,1,1,2,2,2,7,10,15
14,40,3,5,12,Florida,18804580,18845785,19093352,19326230,19563166,...,2,19,6,8,6,5,5,2,5,5
15,40,3,5,13,Georgia,9688709,9711810,9801578,9901496,9973326,...,7,17,12,15,23,14,13,13,15,14
16,40,4,9,15,Hawaii,1360307,1363963,1379252,1394905,1408453,...,47,11,9,12,15,28,24,27,48,48
17,40,4,8,16,Idaho,1567657,1570773,1583828,1595441,1611530,...,17,23,19,24,12,11,12,3,1,2
18,40,2,3,17,Illinois,12831572,12840762,12867291,12884119,12898269,...,50,42,45,46,45,47,49,50,49,50
19,40,2,3,18,Indiana,6484061,6490436,6516045,6537640,6568367,...,18,38,34,36,31,30,35,28,25,24
20,40,2,4,19,Iowa,3046872,3050767,3066054,3076097,3093078,...,28,33,31,37,29,26,29,29,26,26
21,40,2,4,20,Kansas,2853126,2858213,2869035,2885361,2893510,...,42,25,36,29,35,34,31,41,42,42
22,40,3,6,21,Kentucky,4339333,4348200,4369488,4386381,4404817,...,26,21,32,33,32,37,32,32,27,29
23,40,3,7,22,Louisiana,4533485,4544532,4575184,4600814,4624577,...,48,14,24,30,30,29,28,31,45,46
24,40,1,1,23,Maine,1328369,1327632,1328150,1327691,1328196,...,38,50,49,50,48,38,48,35,31,35
25,40,3,5,24,Maryland,5773798,5788642,5838991,5887072,5923704,...,24,13,15,21,27,25,26,30,29,30
26,40,1,1,25,Massachusetts,6547790,6566431,6613149,6663158,6713944,...,16,8,23,23,22,20,27,24,22,22
27,40,2,3,26,Michigan,9884117,9877535,9881521,9896930,9913349,...,22,51,48,45,43,39,42,37,33,38
28,40,2,4,27,Minnesota,5303925,5310843,5345668,5376550,5413693,...,15,32,27,28,24,23,23,19,18,18
29,40,3,6,28,Mississippi,2968118,2970536,2978470,2983767,2988797,...,46,41,39,42,42,45,47,44,40,44
30,40,2,4,29,Missouri,5988952,5995976,6009641,6024081,6040658,...,23,35,44,40,36,33,33,33,28,31
31,40,4,8,30,Montana,989409,990722,997221,1003754,1013564,...,33,31,26,27,14,17,17,15,13,17
32,40,2,4,31,Nebraska,1826305,1829536,1840538,1853323,1865414,...,29,27,29,26,26,19,20,18,20,21
33,40,4,8,32,Nevada,2700679,2702464,2712799,2744566,2776972,...,10,43,35,10,8,6,6,6,3,1
34,40,1,1,33,New Hampshire,1316464,1316777,1319815,1323962,1326408,...,36,47,43,38,41,27,34,23,21,23
35,40,1,2,34,New Jersey,8791962,8799624,8827783,8845483,8858362,...,21,40,37,41,44,42,40,43,35,36
36,40,4,8,35,New Mexico,2059180,2064588,2080395,2087549,2092792,...,39,12,21,35,39,49,45,39,41,40
37,40,1,2,36,New York,19378124,19400080,19498514,19574549,19628043,...,51,36,30,32,37,40,41,46,47,47
38,40,3,5,37,North Carolina,9535736,9574293,9656754,9749123,9843599,...,5,4,16,17,16,15,14,12,14,10
39,40,2,4,38,North Dakota,672576,674710,685136,701116,721999,...,37,7,3,2,1,1,1,42,38,19
40,40,2,3,39,Ohio,11536757,11539327,11543463,11548369,11576576,...,19,48,50,48,40,36,39,38,32,37
41,40,3,7,40,Oklahoma,3751583,3759632,3787821,3818600,3853205,...,31,20,22,22,19,24,18,25,36,33
42,40,4,9,41,Oregon,3831075,3837532,3871728,3899118,3922908,...,14,28,14,25,28,12,11,4,9,11
43,40,1,2,42,Pennsylvania,12702873,12711158,12744583,12766827,12776621,...,25,45,40,44,46,41,46,45,39,39
44,40,1,1,44,Rhode Island,1052957,1053938,1053536,1054601,1055122,...,41,39,51,47,47,43,43,40,43,41
45,40,3,5,45,South Carolina,4625381,4635656,4671422,4717112,4764153,...,9,18,20,16,13,10,10,11,11,9
46,40,2,4,46,South Dakota,814198,816165,823484,833496,842270,...,34,16,13,9,9,18,22,14,12,13
47,40,3,6,47,Tennessee,6346286,6355301,6397410,6451281,6493432,...,11,29,25,20,25,21,19,17,16,16
48,40,3,7,48,Texas,25146114,25242679,25646227,26089620,26489464,...,1,5,2,3,4,3,3,8,7,8
49,40,4,8,49,Utah,2763891,2775334,2814216,2853467,2897927,...,12,3,5,6,3,8,8,1,2,3
50,40,1,1,50,Vermont,625744,625880,626979,626063,626212,...,40,49,46,51,49,50,44,49,37,32
51,40,3,5,51,Virginia,8001055,8023680,8100469,8185229,8253053,...,13,9,11,13,21,22,21,21,19,20
52,40,4,9,53,Washington,6724540,6742902,6821655,6892876,6962906,...,6,10,7,14,10,9,7,5,4,6
53,40,3,5,54,West Virginia,1853001,1854214,1856074,1856764,1853873,...,49,44,47,49,51,51,51,51,50,51
54,40,2,3,55,Wisconsin,5687282,5690479,5704755,5719855,5736952,...,20,46,41,39,34,32,38,36,30,27
55,40,4,8,56,Wyoming,563773,564483,567224,576270,582123,...,43,34,33,4,11,44,25,47,51,45
56,40,X,X,72,Puerto Rico,3726157,3721525,3678732,3634488,3593077,...,X,X,X,X,X,X,X,X,X,X

In [7]:
pd.merge(state_df, renamed_state_df,)
merge_df = pd.merge(state_df,renamed_state_df[['state','POPESTIMATE2010','POPESTIMATE2016','NRANK_POPEST2016','NRANK_NPCHG2010']], how='left')
merge_df

,percent_above_poverty_rate,percent_educational_attainment,percent_non_religious,percent_peace_index,state,POPESTIMATE2010,POPESTIMATE2016,NRANK_POPEST2016,NRANK_NPCHG2010
0,88.3,38.2,67,59.92,Massachusetts,6566431,6826022,15,9
1,89.6,37.3,46,37.10,Maryland,5788642,6004692,19,12
2,87.9,35.9,53,49.48,Colorado,5048281,5540921,21,8
3,89.2,35.6,57,56.12,Connecticut,3579125,3578674,29,30
4,88.9,34.5,45,47.38,New Jersey,8799624,8874516,11,21
5,88.2,34.0,39,50.46,Virginia,8023680,8410946,12,6
6,87.8,33.1,66,69.06,Vermont,625880,623644,50,49
7,84.1,32.4,54,45.56,New York,19400080,19641589,4,7
8,90.8,32.0,67,68.98,New Hampshire,1316777,1342373,41,48
9,88.6,31.5,51,67.72,Minnesota,5310843,5523409,22,23
10,86.8,31.0,55,64.36,Washington,6742902,7294680,13,10
11,85.7,30.6,49,42.16,Illinois,12840762,12826895,5,16
12,85.2,30.5,51,64.24,Rhode Island,1053938,1057063,43,46
13,83.6,29.9,51,45.24,California,37320903,39209127,1,2
14,88.5,29.6,53,64.32,Hawaii,1363963,1428105,40,33
15,86.5,29.5,45,48.54,Kansas,2858213,2911263,35,29
16,83.6,29.2,52,58.56,Oregon,3837532,4091404,27,24
17,87.0,28.7,48,37.04,Delaware,899595,949216,45,43
18,88.2,28.5,36,65.54,Utah,2775334,3042613,31,13
19,81.6,27.5,34,39.20,Georgia,9711810,10304763,8,5
20,84.8,27.4,52,54.54,Montana,990722,1040863,44,44
21,87.7,27.4,46,61.46,Nebraska,1829536,1905924,37,35
22,86.0,26.9,66,73.84,Maine,1327632,1331370,42,50
23,88.6,26.6,55,44.98,Alaska,713906,741504,48,32
24,82.8,26.5,35,45.72,North Carolina,9574293,10156679,9,4
25,86.4,26.4,47,52.50,Pennsylvania,12711158,12783538,6,19
26,88.9,25.8,47,65.12,North Dakota,674710,754353,47,40
27,86.8,25.7,55,53.96,Wisconsin,5690479,5772958,20,36
28,81.8,25.6,47,35.66,Arizona,6407774,6945452,14,11
29,82.8,25.5,36,35.96,Texas,25242679,27937492,2,1
30,83.4,25.3,46,32.70,Florida,18845785,20629982,3,3
31,79.4,25.3,43,42.94,New Mexico,2064588,2092789,36,27
32,84.5,25.2,40,35.90,Missouri,5995976,6087203,18,22
33,87.7,25.1,45,62.70,Iowa,3050767,3131785,30,31
34,85.9,25.1,41,53.64,South Dakota,816165,862890,46,41
35,83.8,24.6,47,46.12,Michigan,9877535,9951890,10,51
36,82.1,24.3,30,36.44,South Carolina,4635656,4958235,23,15
37,84.2,24.1,42,53.44,Ohio,11539327,11635003,7,38
38,85.2,23.9,49,55.48,Idaho,1570773,1682930,39,37
39,89.4,23.8,46,54.72,Wyoming,564483,584290,51,47
40,81.8,23.0,27,31.74,Tennessee,6355301,6645011,16,17
41,83.4,22.7,34,37.78,Oklahoma,3759632,3926769,28,20
42,84.8,22.5,46,53.10,Indiana,6490436,6633344,17,25
43,80.8,22.0,23,36.60,Alabama,4785448,4864745,24,28
44,84.6,21.8,51,32.64,Nevada,2702464,2919772,34,42
45,80.1,21.4,29,19.02,Louisiana,4544532,4678215,25,14
46,81.0,21.0,37,53.64,Kentucky,4348200,4438229,26,18
47,78.1,19.6,23,36.60,Mississippi,2970536,2988298,33,39
48,81.3,18.9,30,35.98,Arkansas,2921978,2990410,32,26
49,81.7,17.3,31,56.06,West Virginia,1854214,1830929,38,45

In [8]:
def popChange (row):
    num1 = row['POPESTIMATE2016']
    num2 = row['POPESTIMATE2010']
    change = num1 - num2
    
    return change

In [9]:
merge_df['TOTALPOPCHG'] = merge_df.apply (lambda row: popChange (row),axis=1)

merge_df.head()

,percent_above_poverty_rate,percent_educational_attainment,percent_non_religious,percent_peace_index,state,POPESTIMATE2010,POPESTIMATE2016,NRANK_POPEST2016,NRANK_NPCHG2010,TOTALPOPCHG
0,88.3,38.2,67,59.92,Massachusetts,6566431,6826022,15,9,259591
1,89.6,37.3,46,37.10,Maryland,5788642,6004692,19,12,216050
2,87.9,35.9,53,49.48,Colorado,5048281,5540921,21,8,492640
3,89.2,35.6,57,56.12,Connecticut,3579125,3578674,29,30,-451
4,88.9,34.5,45,47.38,New Jersey,8799624,8874516,11,21,74892

In [10]:
def rankChange (row):
    num1 = int(row['NRANK_POPEST2016'])
    num2 = int(row['NRANK_NPCHG2010'])
    change = num1 - num2
    
    return change

In [11]:
merge_df['TOTALRNKCHANGE'] = merge_df.apply (lambda row: rankChange (row),axis=1)

merge_df.head()

,percent_above_poverty_rate,percent_educational_attainment,percent_non_religious,percent_peace_index,state,POPESTIMATE2010,POPESTIMATE2016,NRANK_POPEST2016,NRANK_NPCHG2010,TOTALPOPCHG,TOTALRNKCHANGE
0,88.3,38.2,67,59.92,Massachusetts,6566431,6826022,15,9,259591,6
1,89.6,37.3,46,37.10,Maryland,5788642,6004692,19,12,216050,7
2,87.9,35.9,53,49.48,Colorado,5048281,5540921,21,8,492640,13
3,89.2,35.6,57,56.12,Connecticut,3579125,3578674,29,30,-451,-1
4,88.9,34.5,45,47.38,New Jersey,8799624,8874516,11,21,74892,-10

In [12]:
renamed_merge = merge_df.rename(columns={"percent_above_poverty_rate":"Percent above Poverty Rate", "percent_educational_attainment":"Percent Bachelor's Degree", "percent_non_religious":"Percent Non-Religious", "percent_peace_index":"Percent Peace Index","state":"State", "POPESTIMATE2010":"Population Estimate 2010", "POPESTIMATE2016":"Population Estimate 2016", "NRANK_POPEST2016":"2016 Rank","NRANK_NPCHG2010":"2010 Rank","TOTALPOPCHG":"Total Population Change","TOTALRNKCHANGE":"Total Rank Change"})
renamed_merge.head()

,Percent above Poverty Rate,Percent Bachelor's Degree,Percent Non-Religious,Percent Peace Index,State,Population Estimate 2010,Population Estimate 2016,2016 Rank,2010 Rank,Total Population Change,Total Rank Change
0,88.3,38.2,67,59.92,Massachusetts,6566431,6826022,15,9,259591,6
1,89.6,37.3,46,37.10,Maryland,5788642,6004692,19,12,216050,7
2,87.9,35.9,53,49.48,Colorado,5048281,5540921,21,8,492640,13
3,89.2,35.6,57,56.12,Connecticut,3579125,3578674,29,30,-451,-1
4,88.9,34.5,45,47.38,New Jersey,8799624,8874516,11,21,74892,-10

In [13]:
state_merge=renamed_merge.set_index('State')
state_merge.head()

,Percent above Poverty Rate,Percent Bachelor's Degree,Percent Non-Religious,Percent Peace Index,Population Estimate 2010,Population Estimate 2016,2016 Rank,2010 Rank,Total Population Change,Total Rank Change
State,,,,,,,,,,
Massachusetts,88.3,38.2,67,59.92,6566431,6826022,15,9,259591,6
Maryland,89.6,37.3,46,37.10,5788642,6004692,19,12,216050,7
Colorado,87.9,35.9,53,49.48,5048281,5540921,21,8,492640,13
Connecticut,89.2,35.6,57,56.12,3579125,3578674,29,30,-451,-1
New Jersey,88.9,34.5,45,47.38,8799624,8874516,11,21,74892,-10

In [14]:
pymysql.install_as_MySQLdb()
engine = create_engine(f"mysql://root:Fr@nklinj1984@localhost/StateETL")
renamed_merge.to_sql(con=engine, name='state_info', if_exists='replace')

In [15]:
state_df.to_sql(con=engine,name='state_json', if_exists='replace')

In [16]:
renamed_state_df.to_sql(con=engine,name='state_csv',if_exists='replace')